### PR TITLE
optionally process comments from tf files as description

### LINKED ISSUE #552: Do not use comments as variable description
### Describe the bug

I have a variables.tf file with `# some comment` and then variables definitions follow
When I generate docs, the comment is used as variable description. I want to avoid that. Is there a config setting I can use to prevent this ?

### How can we reproduce it?

1. Create `variables.tf` with definition
```
# some comment
variable "var1" {
}
```
2. Run 
```
▶ terraform-docs markdown --output-check --show inputs ./
```
Input section will be rendered.

 Output is as follows:
```

## Inputs

| Name | Description | Type | Default | Required |
|------|-------------|------|---------|:--------:|
| <a name="input_var1"></a> [var1](#input\_var1) | some comment | `any` | n/a | yes |
```
## Inputs

| Name | Description | Type | Default | Required |
|------|-------------|------|---------|:--------:|
| <a name="input_var1"></a> [var1](#input\_var1) | some comment | `any` | n/a | yes |

## Inputs

| Name | Description | Type | Default | Required |
|------|-------------|------|---------|:--------:|
| <a name="input_var1"></a> [var1](#input\_var1) | n/a | `any` | n/a | yes |

### Environment information

- terraform-docs version (use `terraform-docs --version`):
```
▶ terraform-docs version                                          

terraform-docs version v0.15.0 darwin/amd64
```
- OS (e.g. Windows, MacOS): MacOS

### PR DESCRIPTION
**Pull request by poojitha-bikki**
### Description of your changes

Fixes #552

This PR includes changes to optionally process comments from `.tf` files as description (when description is not provided in terraform inputs, outputs definition)

- Adds flag **`read-comments`** 

I have:

- [x] Read and followed terraform-docs' [contribution process].
- [x] All tests pass when I run `make test`.

### How has this code been tested
- Added test `TestReadComments()`
- Tested with `make test`
- Tested manually 

> **Manual Test**
> - Create sample tf folder and file
> ```
> mkdir /tmp/test-tf
> cat <<EOF >> /tmp/test-tf/sample.tf
> # some comment
> variable "var1" {
> }
> 
> # some comment
> output "output-var1" {
>   value = null
> }
> EOF
> ```
> 
> - Tested with read-comments as false. Expected - description should be n/a (should not use comment (#some comment) as description)
> ```go
> ▶ go run main.go --read-comments=false --show=inputs,outputs markdown /tmp/test-tf
> ```
> **Result:**
> ## Inputs
> 
> | Name | Description | Type | Default | Required |
> |------|-------------|------|---------|:--------:|
> | <a name="input_var1"></a> [var1](#input\_var1) | n/a | `any` | n/a | yes |
> 
> ## Outputs
> 
> | Name | Description |
> |------|-------------|
> | <a name="output_output-var1"></a> [output-var1](#output\_output-var1) | n/a |
> 
> - Tested with read-comments as true. Expected - 'some comment' is used as description
> ```
> ▶ go run main.go --read-comments=true --show=inputs,outputs markdown /tmp/test-tf  
> ```
> **Result:**
> ## Inputs
> 
> | Name | Description | Type | Default | Required |
> |------|-------------|------|---------|:--------:|
> | <a name="input_var1"></a> [var1](#input\_var1) | some comment | `any` | n/a | yes |
> 
> ## Outputs
> 
> | Name | Description |
> |------|-------------|
> | <a name="output_output-var1"></a> [output-var1](#output\_output-var1) | some comment |
> - Cleanup
> ```
> $ rm -r /tmp/test-tf
> ```

[contribution process]: https://git.io/JtEzg

**TBD**

- ~Config setting that maps to the new option added~ Added new config setting `read-comments`
- ~Tests when option is set to `false`. Currently few tests fail when option is set to `false`~ set default to true (for backwards compatibility). Added new test cases to test when set to `false` and `true`

### CODE REVIEW

**Comment by poojitha-bikki** [comment]
@khos2ow based on our discussion, can you please review.

**Comment by poojitha-bikki** [comment]
I run `make docs` and it resulted in these changes in commit [26b860b3](https://github.com/terraform-docs/terraform-docs/pull/565/commits/26b860b31e05a1f237cb6be56286828d9895bef1)

When default is option is set to `true` [here](https://github.com/terraform-docs/terraform-docs/pull/565/files#diff-5677b4ba310460bbe02aeef47af1bdb1a8693af0eaa1c46f14f02eb20d65e4b8R53) are these changes expected ?

**Comment by khos2ow** [comment]
> When default is option is set to true here technically there shouldn't be any changes to the docs right ?

You are absolutely correct on this, there shouldn't be any changes in `docs/references/` folder. This clearly indicates there's some flaw in the changes in this PR.

**Comment by khos2ow** [comment]
OK, found the issue. It actually doesn't have anything to do with your implementation, the docs generator is faulty. Can you please add the same property (i.e. `VarDescriptionFromComments` or whatever you renamed it to) to https://github.com/terraform-docs/terraform-docs/blob/master/scripts/docs/generate.go#L177 ?

**Comment by poojitha-bikki** [comment]
> https://github.com/terraform-docs/terraform-docs/blob/master/scripts/docs/generate.go#L177

That's exactly where I was looking. Assumed that for options that are not explicitly set, it'll use default. Got it now. Will update. Thanks!

File: internal/terraform/options.go [hunk 1]
```diff
@@ -26,29 +26,31 @@ type SortBy struct {
...
+	Path                       string
+	ShowHeader                 bool
+	HeaderFromFile             string
+	ShowFooter                 bool
+	FooterFromFile             string
+	UseLockFile                bool
+	SortBy                     *SortBy
+	OutputValues               bool
+	OutputValuesPath           string
+	VarDescriptionFromComments bool
```
[the remark this answers is not in the document]
Comment (poojitha-bikki) [reply internal/terraform/options.go]: addressed

**Comment by khos2ow** [comment]
> Assumed that for options that are not explicitly set, it'll use default.

I'm actually in the process of refactoring `Options` which will solve this. It will be as you mentioned, anything now explicitly set in `generate.go` will take the default value.

**Comment by poojitha-bikki** [comment]
@khos2ow added config `ReadComments` (cli flag `read-comments`) for now. Please review. Let me know if the added config setting should be propagated into `printSettings` and `printSDKsettings`

We discussed there might be some overlap with the `description` setting for hcl. But appears `description` solves a different purpose, so my guess is new flag added shouldn't be an issue. Below is an example when both flags are used. 

```
▶ go run main.go tfvars hcl --description --read-comments=true <sample-tf-module>

# some comment
var1 = ""
```
```
▶ go run main.go tfvars hcl --read-comments=true <sample-tf-module>
var1 = ""
```

File: cmd/root.go [hunk 2]
```diff
@@ -81,6 +81,8 @@ func NewCommand() *cobra.Command {
 	cmd.PersistentFlags().BoolVar(&config.OutputValues.Enabled, "output-values", false, "inject output values into outputs (default false)")
 	cmd.PersistentFlags().StringVar(&config.OutputValues.From, "output-values-from", "", "inject output values from file into outputs (default \"\")")
 
+	cmd.PersistentFlags().BoolVar(&config.Settings.ReadComments, "read-comments", true, "use comments for variable description when description is empty")
```
Comment (khos2ow) [inline cmd/root.go:84]: Use of `variable` here is a bit misleading, comments will be read from all the resources, i.e. variable, output, module, etc.

```suggestion
	cmd.PersistentFlags().BoolVar(&config.Settings.ReadComments, "read-comments", true, "use comments as description when description is empty")
```

File: internal/cli/config.go [hunk 3]
```diff
@@ -40,15 +40,16 @@ var flagMappings = map[string]string{
...
+	"anchor":        "settings.anchor",
+	"color":         "settings.color",
+	"default":       "settings.default",
+	"description":   "settings.description",
+	"escape":        "settings.escape",
+	"indent":        "settings.indent",
+	"required":      "settings.required",
+	"sensitive":     "settings.sensitive",
+	"type":          "settings.type",
+	"read-comments": "settings.read-comments",
```
Comment (khos2ow) [inline internal/cli/config.go:52]: Keep this in alphabetic order please.

File: internal/cli/config.go [hunk 4]
```diff
@@ -376,34 +377,36 @@ func (s *sort) validate() error {
...
+	Description  bool `mapstructure:"description"`
+	Escape       bool `mapstructure:"escape"`
+	HideEmpty    bool `mapstructure:"hide-empty"`
+	HTML         bool `mapstructure:"html"`
+	Indent       int  `mapstructure:"indent"`
+	LockFile     bool `mapstructure:"lockfile"`
+	Required     bool `mapstructure:"required"`
+	Sensitive    bool `mapstructure:"sensitive"`
+	Type         bool `mapstructure:"type"`
+	ReadComments bool `mapstructure:"read-comments"`
```
Comment (khos2ow) [inline internal/cli/config.go:392]: Keep this in alphabetic order please.

File: internal/cli/config.go [hunk 5]
```diff
@@ -376,34 +377,36 @@ func (s *sort) validate() error {
...
+		Description:  false,
+		Escape:       true,
+		HideEmpty:    false,
+		HTML:         true,
+		Indent:       2,
+		LockFile:     true,
+		Required:     true,
+		Sensitive:    true,
+		Type:         true,
+		ReadComments: true,
```
Comment (khos2ow) [inline internal/cli/config.go:409]: Keep this in alphabetic order please.

**Review by khos2ow — COMMENTED** [review]
Please look at my comments below. Also please update the new config in:

- `README.md`
- `docs/user-guide/configuration.md`
- `docs/user-guide/configuration/settings.md`

**Comment by khos2ow** [comment]
> Let me know if the added config setting should be propagated into printSettings and printSDKsettings

This should be good as is and it's not necessary as this is an entirely internal config to load the module.

**Comment by khos2ow** [comment]
I realized in no point there's a test with `ReadComments: false`. It might be a good idea to create a test case, `TestReadComments()` in `module_test.go`, and for simplicity you can create `internal/terraform/testdata/read-comments` with one `variable` and one `output` with comments and test-cases of `ReadComments` both `true` and `false`.

File: cmd/root.go (hunk 2 above)
Comment (poojitha-bikki) [reply cmd/root.go:84]: I can be wrong but my understanding is description is only applicable to input variables and output values. If so, does this look ok ?
```suggestion
	cmd.PersistentFlags().BoolVar(&config.Settings.ReadComments, "read-comments", true, "use comments for description of inputs, outputs when description is empty")
```

**Comment by poojitha-bikki** [comment]
- [ ] Updated docs (added new config setting)
- [ ] Added `TestReadComments()` with testcases and testdata to test new config `read-comments`

File: cmd/root.go (hunk 2 above)
Comment (khos2ow) [reply cmd/root.go:84]: You are correct, it was my bad not to clarify it more. As part of #550 we are going to expand it to all resources; i.e. modules, and resource as well.

Comment (poojitha-bikki) [reply cmd/root.go:84]: I see, understood. took a look at 550, appears we probably need a different flag for that. Users might want to only use comments for description of (inputs , outputs) and not extract any other comments right. Either case, I can commit your suggestion above. we probably don't have to decide right now.

**Review by khos2ow — APPROVED** [review]
Thank you @poojitha-bikki for all the efforts. lgtm!
would you please now squash your commits into one?

File: internal/terraform/module_test.go [hunk 6]
```diff
@@ -782,6 +784,49 @@ func TestLoadComments(t *testing.T) {
...
+			fileName:     "variables.tf",
+			readComments: true,
+			expected:     "B description",
+		},
+	}
+	for _, tt := range tests {
+		t.Run(tt.name, func(t *testing.T) {
+			assert := assert.New(t)
+			options := NewOptions()
+			options.ReadComments = tt.readComments
```
Comment (poojitha-bikki) [inline internal/terraform/module_test.go:814]: Just one more question @khos2ow. for me, it took a while to figure out that a `true` boolean flag cannot be overriden (to  `false`) with `options.With` and `.WithOverwrite`. [This comment]((https://github.com/terraform-docs/terraform-docs/blob/master/internal/terraform/module_test.go#L43) helped. do you think it'll be helpful to add it here as well ?  I did not want to add an extra comment if it's not needed.

Comment (khos2ow) [reply internal/terraform/module_test.go:814]: That's a very good observation, but you can leave it out for now as `Options` and `Settings` will be deprecated in favor of `Config` as part of #510.

**Comment by poojitha-bikki** [comment]
Thank you @khos2ow for your guidance.
